In [3]:
#import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(x)

[['Banten' 30.0 720000.0]
 ['Jakarta' 40.0 nan]
 ['Semarang' 33.0 5000000.0]
 ['Banten' 38.0 6000000.0]
 ['Semarang' 50.0 400000.0]
 ['Jakarta' 48.0 2500000.0]
 ['Jakarta' 29.0 500000.0]
 ['Banten' 37.0 1000000.0]
 ['Semarang' nan 1500000.0]
 ['Banten' 35.0 500000.0]]


In [6]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [8]:
print(x)

[['Banten' 30.0 720000.0]
 ['Jakarta' 40.0 2013333.3333333333]
 ['Semarang' 33.0 5000000.0]
 ['Banten' 38.0 6000000.0]
 ['Semarang' 50.0 400000.0]
 ['Jakarta' 48.0 2500000.0]
 ['Jakarta' 29.0 500000.0]
 ['Banten' 37.0 1000000.0]
 ['Semarang' 37.77777777777778 1500000.0]
 ['Banten' 35.0 500000.0]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [27]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 61666.666666666664]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 50000.0]
 [1.0 0.0 0.0 48.0 58000.0]
 [0.0 0.0 1.0 50.0 52000.0]
 [1.0 0.0 0.0 48.0 58000.0]
 [0.0 1.0 0.0 40.22222222222222 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)


In [13]:
print(x_train)

[[0.0 1.0 0.0 29.0 500000.0]
 [0.0 0.0 1.0 50.0 400000.0]
 [1.0 0.0 0.0 30.0 720000.0]
 [1.0 0.0 0.0 38.0 6000000.0]
 [0.0 1.0 0.0 40.0 2013333.3333333333]
 [1.0 0.0 0.0 37.0 1000000.0]
 [0.0 0.0 1.0 37.77777777777778 1500000.0]
 [0.0 1.0 0.0 48.0 2500000.0]]


In [14]:
print(x_test)

[[0.0 0.0 1.0 33.0 5000000.0]
 [1.0 0.0 0.0 35.0 500000.0]]


In [15]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [16]:
print(y_test)

[0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 1.0 0.0 -1.3926660341627408 -0.771990407248127]
 [0.0 0.0 1.0 1.6154925996287794 -0.8300711902385817]
 [1.0 0.0 0.0 -1.249420384934573 -0.6442126846691267]
 [1.0 0.0 0.0 -0.10345519110923207 2.422452657226881]
 [0.0 1.0 0.0 0.18303610734710318 0.10696544200742064]
 [1.0 0.0 0.0 -0.2467008403373997 -0.48158649229585354]
 [0.0 0.0 1.0 -0.13528755760438033 -0.19118257734358007]
 [0.0 1.0 0.0 1.3290013011724442 0.38962525256096686]]


In [19]:
print(x_test)

[[0.0 0.0 1.0 -0.8196834372500702 1.841644827322334]
 [1.0 0.0 0.0 -0.533192138793735 -0.771990407248127]]
